# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u4hNDCcWyZIQSuBEcyrOE7Zj5Z9ltzMJ
"""

# ============================================
# SEL 1: Instalasi dependensi
# ============================================

!pip install -U google-generativeai chromadb sentence-transformers gradio -q

# ============================================
# SEL 2: Import semua library
# ============================================

import google.generativeai as genai
import chromadb
from sentence_transformers import SentenceTransformer
import os
import warnings
warnings.filterwarnings("ignore")

# ============================================
# SEL 3: Konfigurasi API Key
# ============================================

from google.colab import userdata

GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')

os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY
genai.configure(api_key=GOOGLE_API_KEY)

print("API key berhasil dikonfigurasi!")

# ============================================
# SEL 4: Knowledge base
# ============================================

dokumen = [
    """
    MENURUNKAN BERAT BADAN - PRINSIP DASAR
    Untuk turun berat badan, prinsip utamanya gampang: kalori yang keluar harus lebih besar dari kalori yang masuk (kalori defisit).
    Tapi jangan asal defisit ya, harus tetap sehat. Biasanya defisit 300-500 kkal per hari sudah cukup.
    Gabungkan dengan olahraga yang bener, hasilnya bakal lebih maksimal dan nggak bikin otot loyo.
    """,

    """
    MENURUNKAN BERAT BADAN - CARDIO
    Cardio adalah raja kalau mau bakar lemak. Jenis cardio yang efektif:
    1. Lari/jogging - bisa bakar 400-600 kkal per jam, tergantung kecepatan dan berat badan.
    2. Bersepeda - ramah lutut, bakar sekitar 300-500 kkal per jam.
    3. Skipping/lompat tali - super efektif, bakar 700-1000 kkal per jam!
    4. Berenang - full body workout, bakar 400-700 kkal per jam, cocok buat yang punya masalah sendi.
    5. Naik tangga/stair climbing - target paha dan bokong, bakar 300-500 kkal per jam.
    Tips: Lakukan cardio 3-5 kali seminggu, durasi 30-45 menit. Jangan lupa pemanasan dan pendinginan.
    """,

    """
    MENURUNKAN BERAT BADAN - HIIT (High Intensity Interval Training)
    HIIT itu teknik olahraga yang ganti-ganti antara intensitas tinggi dan rendah.
    Contoh: sprint 30 detik, jalan pelan 1 menit, ulang 8-10 kali.
    Kelebihan HIIT: pembakaran kalori tetap lanjut sampai beberapa jam SETELAH olahraga (efek afterburn/EPOC).
    Durasi HIIT cuma 15-25 menit tapi hasilnya bisa setara cardio 45 menit.
    Contoh gerakan HIIT: burpees, mountain climbers, jump squats, high knees, plank jacks.
    Lakukan HIIT 2-3 kali seminggu aja, jangan kebanyakan soalnya bikin recovery berat.
    """,

    """
    MENURUNKAN BERAT BADAN - STRENGTH TRAINING
    Banyak orang salah kaprah, mikir mau kurus ya cuma cardio doang. Padahal angkat beban juga penting banget!
    Kenapa? Karena otot itu butuh kalori lebih banyak buat dipertahankan dibanding lemak.
    Jadi makin banyak otot, metabolisme basalmu makin tinggi, artinya kamu bakar kalori lebih banyak bahkan lagi tidur.
    Gerakan yang direkomendasikan: squat, deadlift, bench press, lat pulldown, overhead press, row.
    Lakukan strength training 2-4 kali seminggu. Fokus ke compound movement yang melibatkan banyak otot sekaligus.
    """,

    """
    MENAIKKAN BERAT BADAN - PRINSIP DASAR
    Untuk naik berat badan, kebalikan dari diet: kalori masuk harus lebih besar dari kalori keluar (kalori surplus).
    Tapi jangan asal makan junk food ya! Surplus yang sehat itu sekitar 300-500 kkal di atas kebutuhan.
    Fokusnya bukan cuma naik timbangan, tapi naiknya otot, bukan lemak. Makanya olahraga wajib!
    Tanpa olahraga, surplus kalori cuma bakal jadi lemak doang.
    """,

    """
    MENAIKKAN BERAT BADAN - STRENGTH TRAINING (FOKUS BESAR)
    Ini bagian paling penting buat kamu yang mau naik berat badan dengan cara sehat.
    Kuncinya: angkat beban berat dengan repetisi sedikit (6-12 rep per set), tapi intensitas tinggi.
    Latihan yang paling efektif:
    1. Squat - raja semua latihan, target kaki dan core. 4 set x 8-10 rep.
    2. Deadlift - latihan paling berat, target punggung bawah, glute, hamstring. 4 set x 6-8 rep.
    3. Bench Press - target dada, bahu depan, trisep. 4 set x 8-10 rep.
    4. Barbell Row - target punggung tengah, bicep. 4 set x 8-12 rep.
    5. Overhead Press - target bahu, trisep. 3 set x 8-10 rep.
    Latihan 3-4 kali seminggu. Pakai prinsip progressive overload: pelan-pelan naikkan beban tiap minggu.
    """,

    """
    MENAIKKAN BERAT BADAN - NUTRISI PENDUKUNG
    Olahraga aja nggak cukup, nutrisi juga harus bener:
    1. Protein: 1.6-2.2 gram per kg berat badan. Sumber: ayam, daging sapi, telur, ikan, tahu, tempe, whey protein.
    2. Karbohidrat: Jangan takut karbo! Ini energi utama buat latihan. Sumber: nasi, pasta, oatmeal, kentang, ubi.
    3. Lemak sehat: Penting buat hormon testosterone. Sumber: alpukat, kacang-kacangan, minyak zaitun, ikan salmon.
    4. Makan sering: 4-6 kali sehari dengan porsi sedang, lebih mudah dibanding 3 kali makan porsi besar.
    5. Minum susu: Kalau nggak lactose intolerant, susu full cream itu jawaban buat bulk murah dan efektif.
    """,

    """
    TIPS UMUM UNTUK SEMUA PROGRAM
    1. Tidur cukup 7-9 jam. Otot tumbuh dan lemak dibakar saat tidur, bukan saat latihan!
    2. Minum air minimal 2-3 liter per hari. Dehidrasi bikin metabolisme lambat dan energi drop.
    3. Konsistensi lebih penting dari intensitas. Latihan biasa tiap minggu lebih baik daripada latihan gila-gilaan tapi cuma seminggu.
    4. Catat progres: timbang badan, ukur lingkar badan, foto before-after, dan catat beban yang dipakai.
    5. Jangan terlalu fokus ke timbangan. Kalau kamu latihan beban, berat badan bisa naik tapi lemak berkurang (karena otot lebih padat).
    6. Istirahat cukup antar set (60-90 detik) dan antar hari latihan (minimal 1 hari rest per minggu).
    7. Warm up 5-10 menit sebelum latihan dan stretching setelah latihan buat cegah cedera.
    """,

    """
    CONTOH JADWAL LATIHAN TURUN BERAT BADAN (MINGGUAN)
    Senin: Full body strength training (squat, bench press, row, plank) - 45 menit
    Selasa: HIIT 20 menit + abs workout 10 menit
    Rabu: Istirahat atau yoga ringan
    Kamis: Lower body strength (squat, lunges, leg press, calf raise) - 40 menit
    Jumat: Cardio steady state (lari/bersepeda) 35-40 menit
    Sabtu: Upper body strength (bench press, lat pulldown, shoulder press, bicep curl) - 40 menit
    Minggu: Istirahat total
    Catatan: Bisa disesuaikan dengan kondisi masing-masing. Yang penting konsisten!
    """,

    """
    CONTOH JADWAL LATIHAN NAIK BERAT BADAN (MINGGUAN)
    Senin: Push day (bench press 4x8, overhead press 3x10, incline dumbbell press 3x10, tricep pushdown 3x12)
    Selasa: Pull day (deadlift 4x6, barbell row 4x8, lat pulldown 3x10, bicep curl 3x12, face pull 3x15)
    Rabu: Istirahat
    Kamis: Leg day (squat 4x8, leg press 3x10, romanian deadlift 3x10, leg curl 3x12, calf raise 4x15)
    Jumat: Push day (sama seperti Senin, bisa sedikit variasi beban)
    Sabtu: Pull day (sama seperti Selasa)
    Minggu: Istirahat total
    Catatan: Push-Pull-Legs split ini cocok buat intermediate. Untuk beginner, bisa pakai Full Body 3x seminggu dulu.
    """,

    """
    MITOS YANG SERING DIPERCAYA TAPI SALAH
    1. Mitos: "Lari pagi di perut kosong bakar lemak lebih banyak."
       Fakta: Pembakaran lemak total tetap sama dalam sehari. Yang beda cuma sumber energinya. Yang penting total kalori defisit.
    2. Mitos: "Angkat beban bikin cewek jadi kekar kayak bodybuilder."
       Fakta: Cewek punya testosterone jauh lebih rendah dari cowok. Bakal nggak gampang sekurus itu butuh tahunan dan diet ketat.
    3. Mitos: "Sit-up bisa hilangkan lemak perut."
       Fakta: Tidak ada spot reduction (bakar lemak di area tertentu). Sit-up memperkuat otot perut tapi lemaknya tetap ada di atasnya.
    4. Mitos: "Keringat banyak berarti lemak banyak terbakar."
       Fakta: Keringat itu pendingan tubuh, bukan indikator pembakaran lemak. Kamu bisa keringat banyak tanpa olahraga (cuaca panas).
    5. Mitos: "Nggak makan nasi bisa langsung kurus."
       Fakta: Yang bikin gemuk itu kelebihan kalori total, bukan nasi sendiri. Tanpa karbo, kamu jadi lemas dan nggak kuat latihan.
    """,

    """
    OLAHRAGA UNTUK PEMULA YANG BARU MULAI
    Kalau kamu belum pernah olahraga rutin, jangan langsung ngegas berat. Mulai pelan-pelan:
    Minggu 1-2: Jalan cepat 20-30 menit, 3x seminggu. Ditambah basic bodyweight: push up (bisa pakai lutut), squat tanpa beban, plank 15-20 detik.
    Minggu 3-4: Tambah durasi jadi 30-40 menit. Mulai introduce dumbbell ringan (2-5 kg). Push up mulai coba full.
    Minggu 5-6: Mulai masuk gym kalau bisa. Pelajari form yang benar untuk squat, bench press, dan lat pulldown dengan beban ringan.
    Minggu 7-8: Sudah bisa mulai program terstruktur (full body 3x seminggu).
    Kunci buat pemula: Jangan bandingkan diri sama orang lain. Fokus ke konsistensi dan form yang benar, bukan beban yang berat.
    """,
]

print(f"Total dokumen knowledge base: {len(dokumen)} dokumen")

# ============================================
# SEL 5: Text splitting, embedding, simpan ke ChromaDB
# ============================================

def split_text(text, chunk_size=500, overlap=50):
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunks.append(text[start:end])
        start += chunk_size - overlap
    return chunks

all_chunks = []
for doc in dokumen:
    chunks = split_text(doc.strip(), 500, 50)
    all_chunks.extend(chunks)

print(f"Jumlah chunk: {len(all_chunks)}")

embed_model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

embeddings = embed_model.encode(all_chunks)
print("Embedding selesai!")

chroma_client = chromadb.Client()
collection = chroma_client.create_collection("olahraga_bb")

for i, (chunk, emb) in enumerate(zip(all_chunks, embeddings)):
    collection.add(
        ids=[f"chunk_{i}"],
        documents=[chunk],
        embeddings=[emb.tolist()]
    )

print("Vector store berhasil dibuat!")

# ============================================
# SEL 6: Setup Gemini 2.5 Flash + Prompt + Fungsi RAG
# ============================================

gemini_model = genai.GenerativeModel("gemini-2.5-flash")

SYSTEM_PROMPT = """
Kamu adalah EduBot, seorang teman ngobrol yang asyik dan ngerti banget soal olahraga untuk naik dan turun berat badan.
Gunakan bahasa santai seperti lagi ngobrol sama temen, pakai bahasa gaul yang wajar, jangan kaku atau kayak robot.

Aturan kamu:
1. Jawab berdasarkan konteks yang diberikan. Kalau konteksnya nggak cukup, kamu bisa nambahin pengetahuan umum tapi bilang kalau itu bukan dari sumber utama.
2. Jangan pernah bilang "sebagai AI" atau "saya adalah chatbot". Anggap aja kamu temen yang happen kebelakangan soal fitness.
3. Kalau ada yang nanya di luar topik olahraga/fitness, arahkan balik dengan santai.
4. Kasih jawaban yang praktis dan actionable, bukan teori doang.
5. Sering-sering pakai kata "ya", "nih", "sih", "dong", "banget", "kok", "kan" yang wajar.
6. Kalau nanya soal program latihan, kasih detail: berapa set, berapa rep, istirahat berapa lama.
7. Selalu ingetkan buat konsultasi dokter kalau ada kondisi kesehatan tertentu.
"""

safety_settings = {
    "HARM_CATEGORY_HARASSMENT": "BLOCK_NONE",
    "HARM_CATEGORY_HATE_SPEECH": "BLOCK_NONE",
    "HARM_CATEGORY_SEXUALLY_EXPLICIT": "BLOCK_NONE",
    "HARM_CATEGORY_DANGEROUS_CONTENT": "BLOCK_NONE",
}

try:
    gen_config = genai.types.GenerationConfig(
        thinking_config={"thinking_budget": 0}
    )
    print("Thinking dimatikan (respon cepat)")
except Exception:
    gen_config = None
    print("Thinking tetap aktif (respon lebih lambat)")

def chat(message, history=None):
    try:
        query_emb = embed_model.encode([message])

        results = collection.query(
            query_embeddings=query_emb.tolist(),
            n_results=3
        )
        context = "\n\n".join(results['documents'][0])

        full_prompt = f"{SYSTEM_PROMPT}\n\nKonteks yang bisa kamu pakai:\n{context}\n\nPertanyaan: {message}\nJawaban:"

        if gen_config:
            response = gemini_model.generate_content(
                full_prompt,
                safety_settings=safety_settings,
                generation_config=gen_config
            )
        else:
            response = gemini_model.generate_content(
                full_prompt,
                safety_settings=safety_settings
            )

        jawaban = response.text if hasattr(response, 'text') else None

        if jawaban is None or jawaban.strip() == "":
            return "Hmm, Gemini lagi nggak bisa jawab nih. Coba tanya ulang dengan kata-kata yang beda ya!"

        return jawaban

    except Exception as e:
        return f"Waduh, error nih: {type(e).__name__} - {e}. Coba lagi ya!"

print("Fungsi chat siap!")

# ============================================
# SEL 7: Test sebelum launch UI
# ============================================

tes = chat("Gimana cara turun berat badan?", [])
print("--- Hasil Test ---")
print(tes)

# ============================================
# SEL 8: Launch Gradio UI
# ============================================

import gradio as gr

demo = gr.ChatInterface(
    fn=chat,
    title="EduBot Olahraga - Naik & Turun Berat Badan",
    description="Tanya apa aja soal olahraga buat naikin atau turunin berat badan. Bahasa santai, jawaban praktis!",
    examples=[
        "Gimana cara turun berat badan yang efektif?",
        "Aku mau naik berat badan, latihan apa yang harus aku lakukan?",
        "Apa itu HIIT dan cocok nggak buat pemula?",
        "Mitos sit-up bisa hilangkan lemak perut, bener ga sih?",
        "Bikin jadwal latihan seminggu dong buat turun berat badan",
        "Makanan apa yang harus aku makan biar bisa bulk dengan sehat?",
        "Aku pemula total, mau mulai olahraga dari nol, gimana caranya?",
        "Kenapa angkat beban penting buat yang mau diet?",
    ],
)

demo.launch()